export const config = {
  originalPath: "",
  outputPath: "",
  dictionaryPath: "",
  title: "",
  provider: "gemini",
  model: "gemini-3.1-flash-lite-preview",
  apiKeys: [],
  language: "Japanese",
  runner: "api",
  pipeline: ["extraction", "translation", "consistency", "humanization"],
  skipProhibitedContent: true,
  skipHighDemand: true,
  loopSkip: true,
  thinking: "medium",
  debug: false,
};
